### ISSUE TITLE
LibCat使用报错，程序崩溃闪退java.lang.NoSuchMethodError: No static method aspectOf()Lcom/elvishew/xlog/libcat/internal/LogAspect

### ISSUE THREAD

**Issue by Rockets1080** [elvishew/xLog#112]
![image](https://user-images.githubusercontent.com/49021029/128301007-105ecc63-6066-47b9-a957-3250c726f766.png)

**Comment by Rockets1080** [comment]
![image](https://user-images.githubusercontent.com/49021029/128301151-f69baf54-fac3-4271-8c09-4fde7da36eab.png)
![image](https://user-images.githubusercontent.com/49021029/128301279-3e7d3cef-6b00-4e1a-a42c-e2ef7b37606b.png)

**Comment by Rockets1080** [comment]
2021-08-05 14:15:20.252 20551-20551/com.elvishew.xlogsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elvishew.xlogsample, PID: 20551
    java.lang.NoSuchMethodError: No static method aspectOf()Lcom/elvishew/xlog/libcat/internal/LogAspect; in class Lcom/elvishew/xlog/libcat/internal/LogAspect; or its super classes (declaration of 'com.elvishew.xlog.libcat.internal.LogAspect' appears in /data/app/com.elvishew.xlogsample-gzywt7mVC4hS7VLcpVYA7A==/base.apk)
        at com.elvishew.xlogsample.XLogSampleApplication.onCreate(XLogSampleApplication.java:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2021-08-05 14:15:20.257 20551-20620/com.elvishew.xlogsample E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@83ef3d6

**Comment by elvishew** [comment]
Remove the `include 'com.elvishew.xlogsample'` from build.gradle and try again.
