### ISSUE TITLE
小米手机应用双开导致崩溃

### ISSUE THREAD

**Issue by Witype** [elvishew/xLog#129]
`
05-06 16:14:37.468   312  1319 W System.err: java.lang.InterruptedException
05-06 16:14:37.468   312  1319 W System.err: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)

05-06 16:14:37.468   312  1319 W System.err: 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)

05-06 16:14:37.468   312  1319 W System.err: 	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.printer.file.FilePrinter$Worker.enqueue(FilePrinter.java:336)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.printer.file.FilePrinter.println(FilePrinter.java:114)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.printer.PrinterSet.println(PrinterSet.java:39)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.Logger.printlnInternal(Logger.java:597)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.Logger.println(Logger.java:520)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.Logger.d(Logger.java:221)
05-06 16:14:37.468   312  1319 W System.err: 	at com.elvishew.xlog.Logger$Builder.d(Logger.java:1129)

使用小米手机Mi 10 Pro，遇到了以上问题。
ps
1.每一次启动日志文件夹名都会生成新的名称
`

**Comment by elvishew** [comment]
@Witype 请问这是必现问题吗？这部分日志不是崩溃，只是在把日志写入到文件时失败了（因为线程被打断）。

“每一次启动日志文件夹名都会生成新的名称”
需要检查你所配置的命名规则。
