### ISSUE TITLE
What's the problem

### ISSUE THREAD

**Issue by scodemao** [elvishew/xLog#59]
java.lang.NullPointerException: Attempt to get length of null array
        at com.elvishew.xlog.printer.file.FilePrinter.cleanLogFilesIfNecessary(FilePrinter.java:161)
        at com.elvishew.xlog.printer.file.FilePrinter.doPrintln(FilePrinter.java:130)
        at com.elvishew.xlog.printer.file.FilePrinter.access$200(FilePrinter.java:39)
        at com.elvishew.xlog.printer.file.FilePrinter$Worker.run(FilePrinter.java:358)
        at java.lang.Thread.run(Thread.java:776)

**Comment by scodemao** [comment]
i modified this function ,work well

private void cleanLogFilesIfNecessary() {
        File logDir = new File(this.folderPath);
        File[] files = logDir.listFiles();
        if (files != null && files.length > 0) {
            File[] var3 = files;
            int var4 = files.length;

            for (int var5 = 0; var5 < var4; ++var5) {
                File file = var3[var5];
                if (this.cleanStrategy.shouldClean(file)) {
                    file.delete();
                }
            }
        }
    }

**Comment by elvishew** [comment]
Fixed in v1.6.1
