### ISSUE TITLE
XLog混淆怎么配置

### ISSUE THREAD

**Issue by 13186137845** [elvishew/xLog#60]
开启混淆报错
    java.lang.NullPointerException
        at com.elvishew.xlog.printer.file.FilePrinter.cleanLogFilesIfNecessary(Unknown Source)
        at com.elvishew.xlog.printer.file.FilePrinter.doPrintln(Unknown Source)
        at com.elvishew.xlog.printer.file.FilePrinter.access$200(Unknown Source)
        at com.elvishew.xlog.printer.file.FilePrinter$Worker.run(Unknown Source)

**Comment by elvishew** [comment]
@13186137845 It is a bug, already fixed.

Duplicated with #59
